-- Migration: add_avatar_url_and_updated_at_to_profiles
-- Applied to production: 2026-05-12 (Day 4)
-- Pushed via Supabase MCP apply_migration
-- Note: This migration was also generated by Drizzle (drizzle/0001_curious_silver_surfer.sql)

ALTER TABLE "profiles" ADD COLUMN "avatar_url" text;
ALTER TABLE "profiles" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
